# Tensorflow

Tensorflow es una librería de uso libre que permite realizar operaciones matemáticas. Es simbolica y dinámica.

A día de hoy, existen dos modos de utilizar tensorflow: Grafós e Eager Execution. Además, para la construcción de redes neuronales artificiales modulos que facilitan el trabajo como lo son layers, keras, train, y nn.

## Grafos

En este curso se utilizaran los grafos. Cuando creamos las arquitecturas de esta forma, hay que recortar que primero debemos definir la estructura--donde ninguna operación se está ejecutando--, crear una sesion, y finalmente introducir la información que se deasea al grafo al mismo tiempo que indicar de la salida de que nodo nos interesa.

## Elementos importantes
- Tensor: Contenedor donde se contendrá la información de manera matricial.
- Placeholder: Nodos de por los que se introduce la información al grafo.
- Variable: Contiene variables que requieren ser inicializadas y que pueden cambiar en el transcurso de la ejecución del grafo.
- Constant: Tensor que contendrá valores inmutables durante la ejecución del grafo.
- Session: Es la forma de encapsular al grafo para ser ejecutado.
- run: Método de Session utilizado para ejecutar e introducir información en el grafo.
- Feed Dict: Diccionario en el que se indicará que información que se introducirá al grafo, y a que Placeholder.

## Notas importantes

En tensorflow el tipo de números es importante, si una constante se define con un int32 de python, la constante será creada con el tipo tf.int32. Si en una operación no hay compatibilidad de tipo de datos, habrá que cambiarlo mediante tf.cast.

In [ ]:
import tensorflow as tf 

# Constantes

In [2]:
# Definición de constantes
a = tf.constant(1)
b = tf.constant(1.5,name='b')

print(a)
print(b)

Tensor("Const:0", shape=(), dtype=int32)
Tensor("b:0", shape=(), dtype=float32)


## Operaciones

In [3]:
c = tf.add(a,b,name='suma')

print(c)

TypeError: Input 'y' of 'Add' Op has type float32 that does not match type int32 of argument 'x'.

En la celda anterior se trató de de sumar dos constantes con tipos de datos diferentes que resultó en un error. Para corregir esto debemos utilizar tf.cast.

In [4]:
c = tf.add(tf.cast(a,dtype=tf.float32),b,name='suma')

print(c)

Tensor("suma_1:0", shape=(), dtype=float32)


## Ejecución

Creamos la sesion.

In [5]:
sess = tf.Session()

Solicitamos la salida del nodo c.

In [6]:
resultado = sess.run(c)

print(resultado)

2.5


Al utilizar tensorflow tambipen podemos utilizar operadores normales de python. Otra manera de realizar la suma anterior es de la forma siguiente.

In [7]:
d = tf.cast(a,tf.float32) + b

print(d)

Tensor("add:0", shape=(), dtype=float32)


In [8]:
resultado = sess.run(d)

print(resultado)

2.5


## Variables

In [9]:
# Definicion de variables
a = tf.Variable(100.)

print(a)

<tf.Variable 'Variable:0' shape=() dtype=float32_ref>


In [10]:
resultado = sess.run(a)
print(resultado)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}} = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

Notese el error de la celda anterior, este debido a que las variables requieren ser inicializadas. De forma que se continua de la forma siguiente.

In [11]:
# Inicializamos las variables
sess.run(tf.global_variables_initializer())

In [12]:
resultado = sess.run(a)

print(resultado)

100.0


Reducción de una variable iterativamente.

In [13]:
b = a - 1.

for i in range(5):
    resultado = sess.run(b)
    print(resultado)

99.0
99.0
99.0
99.0
99.0


El tratar de reducir el valor de una variable como se vió en la celda anterior resultará en fracaso. Se debe usar otro nodo para interactuar con su valor.

In [14]:
b = tf.assign_sub(a,1.)

for i in range(5):
    resultado = sess.run(b)
    print(resultado)

99.0
98.0
97.0
96.0
95.0


## Placeholders

In [15]:
# Definicion de un placeholder
a = tf.placeholder(dtype=tf.float32,shape=[],name='ph_a')

print(a)

Tensor("ph_a:0", shape=(), dtype=float32)


In [16]:
# Feed Dict - Forma de indicar la informacion y el placeholder 
# al que va dirigido
fd = {a:5.}

# Creamos una constante
b = tf.constant(2.)

# Definimos las operaciones
c = tf.multiply(a,b,name='Multiplicacion')
d = a*b

# Solicitamos la salida de ambas operaciones
resultado_c,resultado_d = sess.run([c,d],feed_dict=fd)

print(resultado_c)
print(resultado_d)

10.0
10.0


## Matrices

In [17]:
a = tf.placeholder(tf.float32,shape=[2,2])
b = tf.placeholder(tf.float32,shape=[2,1])

c = tf.matmul(a,b) # Producto interno
d = tf.multiply(a,b) # Miultiplicacion elemento por elemento. Broadcasting

# Feed Dict
input_data = {a:[[1,3],
                 [2,4]],
              b:[[5],
                 [6]]}

resultado_a,resultado_b = sess.run([c,d],feed_dict=input_data)

print(resultado_a)
print(resultado_b)

[[23.]
 [34.]]
[[ 5. 15.]
 [12. 24.]]


In [18]:
a = tf.placeholder(tf.int32,shape=[4,5,3])
b = tf.constant(2)

c = a*b

inp = {a:[[[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]],
          [[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]],
          [[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]],
          [[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]]]}

resultado = sess.run(c,feed_dict=inp)

print(resultado[:,:,0],'\n')
print(resultado[:,:,1],'\n')
print(resultado[:,:,2])

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]] 

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]] 

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


## Entrada no definida completamente

In [19]:
a = tf.placeholder(tf.bool,shape=[None,3])

inp1 = {a:[[False,True,False]]}

inp2 = {a:[[False,False,True],
           [True,False,False],
           [True,False,True]]}

resultado1 = sess.run(a,feed_dict=inp1)
resultado2 = sess.run(a,feed_dict=inp2)

print(resultado1,'\n')
print(resultado2,'\n')

[[False  True False]] 

[[False False  True]
 [ True False False]
 [ True False  True]] 



## Remoldear Tensor

In [20]:
a = tf.placeholder(tf.int32,shape=[4,4])
# Remoldea el tensor
b = tf.reshape(a,shape=[2,2,2,2])

fd = {a:[[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12],
         [13,14,15,16]]}

resultado = sess.run(b,feed_dict=fd)

# Imprime la nueva forma
print(resultado.shape)

(2, 2, 2, 2)


Una vez que terminamos con la sesion debemos cerrarla.

In [21]:
sess.close()